apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: component-g
  namespace: shbose
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: my-big-application
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: component-g
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
      creationTimestamp: null
      generateName: component-g-
      namespace: shbose
    spec:
      params:
      - name: git-url
        value: https://github.com/sbose78/devfile-sample-code-with-quarkus
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:shbose-component-g-$(tt.params.git-revision)
      - name: dockerfile
        value: src/main/docker/Dockerfile.jvm.staged
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle@sha256:2205a29208fa686b47f841819f7abedb64adb93935493693892d0e18bbdbb77e
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: component-g/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
