apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-g
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-g
    app.kubernetes.io/part-of: my-big-application
  name: component-g
  namespace: shbose
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: component-g
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: component-g
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:shbose-component-g
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
